-- REVIEW CANDIDATE ONLY. Not an active Supabase migration.
-- Filename generated by Supabase CLI 2.20.3 in GitHub Actions run 33886952900.
-- This combined baseline is intentionally stored outside supabase/migrations.
-- It is executable only in the disposable database gralha_baseline_ci.
-- No user, conversation, sale, broker/team seed, secret, or credential is included.
-- Production rollout still requires separate history reconciliation and approval.

-- BEGIN COMPONENT: tests/fixtures/identity_baseline_candidate.sql
-- TEST CANDIDATE ONLY. Not a migration or a production authorization.
-- Fresh identity/RBAC baseline: no privileged email and no user backfill.
do $$ begin
  if current_database() <> 'gralha_baseline_ci' then
    raise exception 'Only disposable gralha_baseline_ci is allowed';
  end if;
end $$;

create schema if not exists private;

-- Prevent future project objects from inheriting broad API grants.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated;

create type public.app_role as enum ('super_admin', 'viewer');
create type public.profile_status as enum ('invited', 'active', 'disabled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  status public.profile_status not null default 'invited',
  created_at timestamptz not null default now(),
  status_updated_at timestamptz not null default now(),
  activated_at timestamptz,
  disabled_at timestamptz,
  display_name text,
  access_role text not null default 'team_manager',
  updated_at timestamptz not null default now(),
  constraint profiles_access_role_valid check (
    access_role in ('ceo', 'cso', 'cmo', 'store_director', 'team_manager')
  )
);

create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique
    references public.profiles(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now()
);

create or replace function public.has_role(
  _user_id uuid,
  _role public.app_role
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles as user_role
    join public.profiles as profile on profile.id = user_role.user_id
    where user_role.user_id = _user_id
      and user_role.role = _role
      and profile.status = 'active'
  )
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.has_role((select auth.uid()), 'super_admin'::public.app_role)
$$;

create or replace function public.get_my_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select user_role.role
  from public.user_roles as user_role
  join public.profiles as profile on profile.id = user_role.user_id
  where user_role.user_id = (select auth.uid())
    and profile.status = 'active'
  limit 1
$$;

create or replace function public.is_active_user(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = _user_id and status = 'active'
  )
$$;

create or replace function public.is_active_super_admin(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.has_role(_user_id, 'super_admin'::public.app_role)
$$;

create or replace function private.current_user_is_executive()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.status = 'active'
      and profile.access_role in ('ceo', 'cso', 'cmo')
  )
$$;

create or replace function public.sync_validation_user_access()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(nullif(btrim(new.email), ''));
  resolved_status public.profile_status;
begin
  if normalized_email is null then
    raise exception 'Portal profile requires an email';
  end if;

  resolved_status := case
    when new.email_confirmed_at is not null then 'active'::public.profile_status
    else 'invited'::public.profile_status
  end;

  insert into public.profiles (
    id, email, status, status_updated_at, activated_at
  )
  values (
    new.id,
    normalized_email,
    resolved_status,
    now(),
    case when resolved_status = 'active' then now() else null end
  )
  on conflict (id) do update
  set email = excluded.email,
      status = case
        when public.profiles.status = 'disabled'
          then 'disabled'::public.profile_status
        else excluded.status
      end,
      status_updated_at = now(),
      activated_at = coalesce(
        public.profiles.activated_at,
        excluded.activated_at
      );

  -- Roles and portal scope are explicit administrative decisions.
  insert into public.user_roles (user_id, role)
  values (new.id, 'viewer')
  on conflict (user_id) do nothing;

  return new;
end
$$;

create trigger on_validation_auth_user_access
after insert or update of email, email_confirmed_at on auth.users
for each row execute function public.sync_validation_user_access();

revoke all on function public.has_role(uuid, public.app_role)
  from public, anon, authenticated, service_role;
revoke all on function public.is_super_admin()
  from public, anon, authenticated, service_role;
revoke all on function public.get_my_role()
  from public, anon, authenticated, service_role;
revoke all on function public.is_active_user(uuid)
  from public, anon, authenticated, service_role;
revoke all on function public.is_active_super_admin(uuid)
  from public, anon, authenticated, service_role;
revoke all on function private.current_user_is_executive()
  from public, anon, authenticated, service_role;
revoke all on function public.sync_validation_user_access()
  from public, anon, authenticated, service_role;

grant execute on function public.has_role(uuid, public.app_role)
  to authenticated, service_role;
grant execute on function public.is_super_admin()
  to authenticated, service_role;
grant execute on function public.get_my_role()
  to authenticated, service_role;
grant execute on function public.is_active_user(uuid)
  to authenticated, service_role;
grant execute on function public.is_active_super_admin(uuid)
  to authenticated, service_role;
grant usage on schema private to authenticated;
grant execute on function private.current_user_is_executive() to authenticated;

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;

revoke all on table public.profiles from public, anon, authenticated;
revoke all on table public.user_roles from public, anon, authenticated;
grant select on table public.profiles to authenticated;
grant select on table public.user_roles to authenticated;
grant all on table public.profiles to service_role;
grant all on table public.user_roles to service_role;

create policy profiles_select_self_or_executive
on public.profiles for select to authenticated
using (
  id = (select auth.uid())
  or (select private.current_user_is_executive())
);

create policy "Users and superadmins can view roles"
on public.user_roles for select to authenticated
using (
  user_id = (select auth.uid())
  or (select public.is_super_admin())
);
-- END COMPONENT: tests/fixtures/identity_baseline_candidate.sql

-- BEGIN COMPONENT: tests/fixtures/commercial_baseline_candidate.sql
-- TEST CANDIDATE ONLY. Structural DDL recovered from catalog metadata.
-- No business rows, broker/team seeds, credentials, or production authorization.
do $$ begin
  if current_database() <> 'gralha_baseline_ci' then
    raise exception 'Only disposable gralha_baseline_ci is allowed';
  end if;
end $$;

create schema if not exists validation;

create table "public"."internal_sales_spreadsheet_rows" (
  "id" bigint generated by default as identity not null,
  "source_file_name" text not null,
  "source_sheet_name" text default 'VENDAS'::text not null,
  "source_row_number" integer not null,
  "sale_year" integer,
  "sale_date" date,
  "property_code" text,
  "broker_name" text,
  "broker_key" text,
  "team_name" text,
  "team_key" text,
  "neighborhood" text,
  "vgv" numeric,
  "row_data" jsonb not null,
  "row_formulas" jsonb default '{}'::jsonb not null,
  "source_updated_through" date not null,
  "imported_at" timestamp with time zone default now() not null
);

create table "public"."sales_team_reference" (
  "id" bigint generated by default as identity not null,
  "source_file_name" text not null,
  "source_row_number" integer not null,
  "sale_date" date not null,
  "property_code" text not null,
  "broker_key" text not null,
  "broker_name" text not null,
  "team_key" text not null,
  "team_name" text not null,
  "source_updated_through" date not null,
  "created_at" timestamp with time zone default now() not null
);

create table "validation"."broker_system_identifiers" (
  "id" bigint generated always as identity not null,
  "broker_id" bigint not null,
  "source_system" text not null,
  "external_id" text not null,
  "valid_from" date,
  "valid_to" date,
  "created_at" timestamp with time zone default now() not null
);

create table "validation"."broker_team_history" (
  "id" bigint generated always as identity not null,
  "broker_id" bigint not null,
  "team_id" bigint not null,
  "valid_from" date not null,
  "valid_to" date,
  "change_source" text not null,
  "recorded_at" timestamp with time zone default now() not null,
  "recorded_by" text not null
);

create table "validation"."brokers" (
  "id" bigint generated always as identity not null,
  "display_name" text not null,
  "normalized_name" text not null,
  "active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "validation"."consolidated_sales" (
  "id" bigint generated always as identity not null,
  "pipeimob_transaction_id" text,
  "vista_deal_id" text,
  "property_code" text,
  "official_sale_date" date,
  "vista_gain_date" date,
  "delay_hours" numeric(12,2),
  "official_value" numeric(16,2),
  "vista_value" numeric(16,2),
  "value_difference" numeric(16,2) generated always as (CASE
    WHEN official_value IS NOT NULL AND vista_value IS NOT NULL THEN vista_value - official_value
    ELSE NULL::numeric
END) stored,
  "commercial_broker_id" bigint,
  "commercial_broker_name_snapshot" text,
  "fiscal_broker_id" bigint,
  "fiscal_broker_name_snapshot" text,
  "team_at_sale_id" bigint,
  "team_name_snapshot" text,
  "reconciliation_status" text not null,
  "issues" text[] default '{}'::text[] not null,
  "match_method" text default 'unmatched'::text not null,
  "match_confidence" numeric(5,4),
  "reconciled_at" timestamp with time zone default now() not null,
  "source_version" text default 'validation-v1'::text not null
);

create table "validation"."pipeimob_sales" (
  "transaction_id" text not null,
  "contract_code" text,
  "property_code" text not null,
  "signature_date" date not null,
  "contract_value" numeric(16,2) not null,
  "fiscal_broker_id" bigint,
  "fiscal_broker_name_snapshot" text,
  "sale_status" text default 'active'::text not null,
  "source_run_id" bigint not null,
  "source_record_hash" text not null,
  "ingested_at" timestamp with time zone default now() not null
);

create table "validation"."reconciliation_events" (
  "id" bigint generated always as identity not null,
  "consolidated_sale_id" bigint not null,
  "event_type" text not null,
  "previous_status" text,
  "new_status" text not null,
  "reason" text,
  "changed_at" timestamp with time zone default now() not null,
  "changed_by" text not null,
  "details" jsonb default '{}'::jsonb not null
);

create table "validation"."source_ingestion_runs" (
  "id" bigint generated always as identity not null,
  "source_system" text not null,
  "source_filename" text,
  "source_sha256" text not null,
  "period_start" date,
  "period_end" date,
  "row_count" integer not null,
  "import_status" text default 'completed'::text not null,
  "imported_at" timestamp with time zone default now() not null,
  "imported_by" text not null,
  "metadata" jsonb default '{}'::jsonb not null
);

create table "validation"."teams" (
  "id" bigint generated always as identity not null,
  "stable_code" text not null,
  "display_name" text not null,
  "active" boolean default true not null,
  "valid_from" date,
  "valid_to" date,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "validation"."vista_gains" (
  "deal_id" text not null,
  "property_code" text,
  "gain_date" date,
  "deal_value" numeric(16,2),
  "commercial_broker_id" bigint,
  "commercial_broker_external_id" text,
  "commercial_broker_name_snapshot" text,
  "stage_name" text,
  "crm_status" text default 'GANHO'::text not null,
  "last_update_at" timestamp with time zone,
  "source_run_id" bigint not null,
  "source_record_hash" text not null,
  "ingested_at" timestamp with time zone default now() not null
);

alter table "public"."internal_sales_spreadsheet_rows" add constraint "internal_sales_spreadsheet_rows_pkey" PRIMARY KEY (id);
alter table "public"."sales_team_reference" add constraint "sales_team_reference_pkey" PRIMARY KEY (id);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_pkey" PRIMARY KEY (id);
alter table "validation"."broker_team_history" add constraint "broker_team_history_pkey" PRIMARY KEY (id);
alter table "validation"."brokers" add constraint "brokers_pkey" PRIMARY KEY (id);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pkey" PRIMARY KEY (id);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_pkey" PRIMARY KEY (transaction_id);
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_pkey" PRIMARY KEY (id);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_pkey" PRIMARY KEY (id);
alter table "validation"."teams" add constraint "teams_pkey" PRIMARY KEY (id);
alter table "validation"."vista_gains" add constraint "vista_gains_pkey" PRIMARY KEY (deal_id);
alter table "public"."internal_sales_spreadsheet_rows" add constraint "internal_sales_spreadsheet_rows_source_key" UNIQUE (source_file_name, source_sheet_name, source_row_number);
alter table "public"."sales_team_reference" add constraint "sales_team_reference_source_key" UNIQUE (source_file_name, source_row_number);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_source_system_external_id_key" UNIQUE (source_system, external_id);
alter table "validation"."broker_team_history" add constraint "broker_team_history_broker_id_team_id_valid_from_key" UNIQUE (broker_id, team_id, valid_from);
alter table "validation"."brokers" add constraint "brokers_normalized_name_key" UNIQUE (normalized_name);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pipeimob_transaction_id_key" UNIQUE (pipeimob_transaction_id);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_deal_id_key" UNIQUE (vista_deal_id);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_source_system_source_sha256_key" UNIQUE (source_system, source_sha256);
alter table "validation"."teams" add constraint "teams_stable_code_key" UNIQUE (stable_code);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_check" CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_external_id_check" CHECK (length(btrim(external_id)) > 0);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_source_system_check" CHECK (source_system = ANY (ARRAY['pipeimob'::text, 'vista'::text, 'internal'::text]));
alter table "validation"."broker_team_history" add constraint "broker_team_history_change_source_check" CHECK (change_source = ANY (ARRAY['vista'::text, 'pipeimob'::text, 'administration'::text, 'import'::text]));
alter table "validation"."broker_team_history" add constraint "broker_team_history_check" CHECK (valid_to IS NULL OR valid_to >= valid_from);
alter table "validation"."brokers" add constraint "brokers_display_name_check" CHECK (length(btrim(display_name)) > 0);
alter table "validation"."brokers" add constraint "brokers_normalized_name_check" CHECK (length(btrim(normalized_name)) > 0);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_match_confidence_check" CHECK (match_confidence IS NULL OR match_confidence >= 0::numeric AND match_confidence <= 1::numeric);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_match_method_check" CHECK (match_method = ANY (ARRAY['vista_deal_id'::text, 'client_property'::text, 'property_value_date'::text, 'property_client_assisted'::text, 'manual'::text, 'unmatched'::text]));
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_official_value_check" CHECK (official_value IS NULL OR official_value >= 0::numeric);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_reconciliation_status_check" CHECK (reconciliation_status = ANY (ARRAY['CONCILIADO'::text, 'PIPEIMOB_SEM_GANHO_VISTA'::text, 'VISTA_SEM_CONTRATO_PIPEIMOB'::text, 'DIVERGENCIA_VALOR'::text, 'DIVERGENCIA_DATA'::text, 'DIVERGENCIA_CORRETOR'::text, 'SEM_VINCULO_AUTOMATICO'::text, 'CANCELADO_OU_REVERTIDO'::text, 'DADO_FONTE_INCOMPLETO'::text]));
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_value_check" CHECK (vista_value IS NULL OR vista_value >= 0::numeric);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_contract_value_check" CHECK (contract_value >= 0::numeric);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_property_code_check" CHECK (length(btrim(property_code)) > 0);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_sale_status_check" CHECK (sale_status = ANY (ARRAY['active'::text, 'cancelled'::text, 'reversed'::text]));
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_transaction_id_check" CHECK (length(btrim(transaction_id)) > 0);
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_event_type_check" CHECK (event_type = ANY (ARRAY['created'::text, 'reconciled'::text, 'status_changed'::text, 'manually_reviewed'::text, 'cancelled'::text, 'reversed'::text]));
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_import_status_check" CHECK (import_status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text, 'rolled_back'::text]));
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_row_count_check" CHECK (row_count >= 0);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_source_system_check" CHECK (source_system = ANY (ARRAY['pipeimob'::text, 'vista'::text, 'manual'::text]));
alter table "validation"."teams" add constraint "teams_check" CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from);
alter table "validation"."teams" add constraint "teams_display_name_check" CHECK (length(btrim(display_name)) > 0);
alter table "validation"."teams" add constraint "teams_stable_code_check" CHECK (length(btrim(stable_code)) > 0);
alter table "validation"."vista_gains" add constraint "vista_gains_crm_status_check" CHECK (crm_status = 'GANHO'::text);
alter table "validation"."vista_gains" add constraint "vista_gains_deal_id_check" CHECK (length(btrim(deal_id)) > 0);
alter table "validation"."vista_gains" add constraint "vista_gains_deal_value_check" CHECK (deal_value IS NULL OR deal_value >= 0::numeric);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."broker_team_history" add constraint "broker_team_history_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."broker_team_history" add constraint "broker_team_history_team_id_fkey" FOREIGN KEY (team_id) REFERENCES validation.teams(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_commercial_broker_id_fkey" FOREIGN KEY (commercial_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_fiscal_broker_id_fkey" FOREIGN KEY (fiscal_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pipeimob_transaction_id_fkey" FOREIGN KEY (pipeimob_transaction_id) REFERENCES validation.pipeimob_sales(transaction_id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_team_at_sale_id_fkey" FOREIGN KEY (team_at_sale_id) REFERENCES validation.teams(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_deal_id_fkey" FOREIGN KEY (vista_deal_id) REFERENCES validation.vista_gains(deal_id) ON DELETE RESTRICT;
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_fiscal_broker_id_fkey" FOREIGN KEY (fiscal_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_source_run_id_fkey" FOREIGN KEY (source_run_id) REFERENCES validation.source_ingestion_runs(id) ON DELETE RESTRICT;
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_consolidated_sale_id_fkey" FOREIGN KEY (consolidated_sale_id) REFERENCES validation.consolidated_sales(id) ON DELETE RESTRICT;
alter table "validation"."vista_gains" add constraint "vista_gains_commercial_broker_id_fkey" FOREIGN KEY (commercial_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."vista_gains" add constraint "vista_gains_source_run_id_fkey" FOREIGN KEY (source_run_id) REFERENCES validation.source_ingestion_runs(id) ON DELETE RESTRICT;

CREATE INDEX internal_sales_spreadsheet_rows_broker_date_idx ON public.internal_sales_spreadsheet_rows USING btree (broker_key, sale_date);
CREATE INDEX internal_sales_spreadsheet_rows_property_date_idx ON public.internal_sales_spreadsheet_rows USING btree (property_code, sale_date);
CREATE INDEX internal_sales_spreadsheet_rows_team_date_idx ON public.internal_sales_spreadsheet_rows USING btree (team_key, sale_date);
CREATE INDEX sales_team_reference_lookup_idx ON public.sales_team_reference USING btree (broker_key, sale_date, property_code);
CREATE INDEX broker_system_identifiers_broker_idx ON validation.broker_system_identifiers USING btree (broker_id);
CREATE INDEX broker_team_history_broker_period_idx ON validation.broker_team_history USING btree (broker_id, valid_from, valid_to);
CREATE INDEX broker_team_history_team_idx ON validation.broker_team_history USING btree (team_id);
CREATE INDEX consolidated_sales_commercial_broker_period_idx ON validation.consolidated_sales USING btree (commercial_broker_id, official_sale_date);
CREATE INDEX consolidated_sales_fiscal_broker_period_idx ON validation.consolidated_sales USING btree (fiscal_broker_id, official_sale_date DESC);
CREATE INDEX consolidated_sales_pending_idx ON validation.consolidated_sales USING btree (reconciliation_status, official_sale_date) WHERE (reconciliation_status <> 'CONCILIADO'::text);
CREATE INDEX consolidated_sales_period_status_idx ON validation.consolidated_sales USING btree (official_sale_date, reconciliation_status);
CREATE INDEX consolidated_sales_team_period_idx ON validation.consolidated_sales USING btree (team_at_sale_id, official_sale_date);
CREATE INDEX pipeimob_sales_fiscal_broker_idx ON validation.pipeimob_sales USING btree (fiscal_broker_id);
CREATE INDEX pipeimob_sales_match_idx ON validation.pipeimob_sales USING btree (property_code, contract_value, signature_date);
CREATE INDEX pipeimob_sales_period_idx ON validation.pipeimob_sales USING btree (signature_date, transaction_id);
CREATE INDEX pipeimob_sales_source_run_idx ON validation.pipeimob_sales USING btree (source_run_id);
CREATE INDEX reconciliation_events_sale_idx ON validation.reconciliation_events USING btree (consolidated_sale_id, changed_at);
CREATE INDEX source_runs_period_idx ON validation.source_ingestion_runs USING btree (source_system, period_start, period_end);
CREATE INDEX vista_gains_commercial_broker_idx ON validation.vista_gains USING btree (commercial_broker_id);
CREATE INDEX vista_gains_match_idx ON validation.vista_gains USING btree (property_code, deal_value, gain_date);
CREATE INDEX vista_gains_period_idx ON validation.vista_gains USING btree (gain_date, deal_id);
CREATE INDEX vista_gains_source_run_idx ON validation.vista_gains USING btree (source_run_id);

-- Defense in depth. The validation schema remains outside the Data API.
alter table "public"."internal_sales_spreadsheet_rows" enable row level security;
alter table "public"."sales_team_reference" enable row level security;
alter table "validation"."broker_system_identifiers" enable row level security;
alter table "validation"."broker_team_history" enable row level security;
alter table "validation"."brokers" enable row level security;
alter table "validation"."consolidated_sales" enable row level security;
alter table "validation"."pipeimob_sales" enable row level security;
alter table "validation"."reconciliation_events" enable row level security;
alter table "validation"."source_ingestion_runs" enable row level security;
alter table "validation"."teams" enable row level security;
alter table "validation"."vista_gains" enable row level security;

revoke all on schema validation from public, anon, authenticated, service_role;
revoke all on all tables in schema validation from public, anon, authenticated, service_role;
revoke all on all sequences in schema validation from public, anon, authenticated, service_role;

revoke all on table public.internal_sales_spreadsheet_rows from public, anon, authenticated;
revoke all on table public.sales_team_reference from public, anon, authenticated;
grant select on table public.internal_sales_spreadsheet_rows to authenticated;
grant select on table public.sales_team_reference to authenticated;
grant all on table public.internal_sales_spreadsheet_rows to service_role;
grant all on table public.sales_team_reference to service_role;
grant usage, select, update on sequence public.internal_sales_spreadsheet_rows_id_seq to service_role;
grant usage, select, update on sequence public.sales_team_reference_id_seq to service_role;

create policy "super admins can read full sales spreadsheet"
on public.internal_sales_spreadsheet_rows for select to authenticated
using (public.is_active_super_admin((select auth.uid())));

create policy "active indicator users can read team reference"
on public.sales_team_reference for select to authenticated
using (public.is_active_user((select auth.uid())));
-- END COMPONENT: tests/fixtures/commercial_baseline_candidate.sql

-- BEGIN COMPONENT: docs/migrations/history-review/20260821133318_add_consolidated_sales_fiscal_broker_index.sql.txt
create index if not exists consolidated_sales_fiscal_broker_period_idx on validation.consolidated_sales (fiscal_broker_id, official_sale_date desc);
-- END COMPONENT: docs/migrations/history-review/20260821133318_add_consolidated_sales_fiscal_broker_index.sql.txt

-- BEGIN COMPONENT: docs/migrations/history-review/20260821133813_create_validation_sales_reconciliation_rpc.sql.txt

create or replace function public.get_validation_sales_reconciliation(
  p_start date,
  p_end date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if p_start is null or p_end is null then
    raise exception 'start and end dates are required';
  end if;
  if p_start > p_end then
    raise exception 'start date cannot be after end date';
  end if;
  if (p_end - p_start) > 366 then
    raise exception 'date range cannot exceed 366 days';
  end if;

  with filtered as (
    select
      cs.*,
      ps.contract_code,
      vg.stage_name,
      case
        when cs.commercial_broker_name_snapshot is not null
         and cs.fiscal_broker_name_snapshot is not null
        then lower(btrim(cs.commercial_broker_name_snapshot))
          <> lower(btrim(cs.fiscal_broker_name_snapshot))
        else null
      end as broker_roles_differ
    from validation.consolidated_sales cs
    left join validation.pipeimob_sales ps
      on ps.transaction_id = cs.pipeimob_transaction_id
    left join validation.vista_gains vg
      on vg.deal_id = cs.vista_deal_id
    where (
      cs.official_sale_date between p_start and p_end
      or (
        cs.official_sale_date is null
        and cs.vista_gain_date between p_start and p_end
      )
    )
  ),
  summary as (
    select jsonb_build_object(
      'official_sales', count(*) filter (
        where pipeimob_transaction_id is not null
      ),
      'official_vgv', coalesce(sum(official_value) filter (
        where pipeimob_transaction_id is not null
      ), 0)::text,
      'matched', count(*) filter (
        where reconciliation_status = 'CONCILIADO'
      ),
      'pipeimob_without_vista_gain', count(*) filter (
        where reconciliation_status = 'PIPEIMOB_SEM_GANHO_VISTA'
      ),
      'vista_without_pipeimob_contract', count(*) filter (
        where reconciliation_status = 'VISTA_SEM_CONTRATO_PIPEIMOB'
      ),
      'value_mismatches', count(*) filter (
        where issues @> array['DIVERGENCIA_VALOR']::text[]
      ),
      'date_mismatches', count(*) filter (
        where issues @> array['DIVERGENCIA_DATA']::text[]
      ),
      'no_automatic_link', count(*) filter (
        where reconciliation_status = 'SEM_VINCULO_AUTOMATICO'
      ),
      'source_data_incomplete', count(*) filter (
        where reconciliation_status = 'DADO_FONTE_INCOMPLETO'
      ),
      'missing_commercial_broker', count(*) filter (
        where vista_deal_id is not null
          and commercial_broker_name_snapshot is null
      )
    ) as value
    from filtered
  ),
  items as (
    select coalesce(
      jsonb_agg(
        jsonb_strip_nulls(
          jsonb_build_object(
            'status', reconciliation_status,
            'issues', to_jsonb(issues),
            'pipeimob_transaction_id', pipeimob_transaction_id,
            'pipeimob_contract_code', contract_code,
            'vista_deal_id', vista_deal_id,
            'property_code', property_code,
            'official_sale_date', official_sale_date,
            'vista_gain_date', vista_gain_date,
            'delay_days', case
              when delay_hours is null then null
              else delay_hours / 24
            end,
            'official_value', official_value::text,
            'vista_value', vista_value::text,
            'value_difference', value_difference::text,
            'commercial_broker', commercial_broker_name_snapshot,
            'fiscal_broker', fiscal_broker_name_snapshot,
            'broker_roles_differ', broker_roles_differ,
            'vista_stage', stage_name
          )
        )
        order by official_sale_date, pipeimob_transaction_id, vista_deal_id
      ),
      '[]'::jsonb
    ) as value
    from filtered
  )
  select jsonb_build_object(
    'contract_version', '1.0',
    'official_source', 'pipeimob_contratos_assinados',
    'commercial_source', 'vista_status_ganho',
    'period', jsonb_build_object(
      'start', p_start,
      'end', p_end
    ),
    'generated_at', to_char(
      now() at time zone 'UTC',
      'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'
    ),
    'summary', summary.value,
    'items', items.value,
    'commercial_broker_limitation',
      'Corretor comercial do Vista; corretor fiscal do Pipeimob preservado separadamente.'
  )
  into result
  from summary cross join items;

  return result;
end;
$$;

revoke all on function public.get_validation_sales_reconciliation(date,date)
  from public, anon, authenticated;
grant execute on function public.get_validation_sales_reconciliation(date,date)
  to service_role;

comment on function public.get_validation_sales_reconciliation(date,date) is
  'Private read-only projection for the directors homologation Edge Function. Pipeimob is official; Vista Status=Ganho supplies commercial ownership.';
-- END COMPONENT: docs/migrations/history-review/20260821133813_create_validation_sales_reconciliation_rpc.sql.txt

-- BEGIN COMPONENT: supabase/migrations/20260830162242_add_manager_team_reference.sql
-- Management interpretation only. Official sales facts (count, date and VGV)
-- continue to come from the live Pipeimob API and commercial ownership from
-- the live Vista API.

create table public.manager_team_reference (
  id bigint generated always as identity primary key,
  manager_key text not null,
  manager_name text not null,
  team_key text not null,
  team_name text not null,
  valid_from date not null,
  valid_to date,
  source_file_name text not null,
  source_sheet_name text not null,
  source_updated_through date,
  evidence_rows integer not null,
  review_required boolean not null default false,
  resolution_method text not null default 'management_spreadsheet_effective_date',
  created_at timestamptz not null default now(),
  constraint manager_team_reference_manager_key_not_blank
    check (btrim(manager_key) <> ''),
  constraint manager_team_reference_manager_name_not_blank
    check (btrim(manager_name) <> ''),
  constraint manager_team_reference_team_key_not_blank
    check (btrim(team_key) <> ''),
  constraint manager_team_reference_team_name_not_blank
    check (btrim(team_name) <> ''),
  constraint manager_team_reference_valid_period
    check (valid_to is null or valid_to >= valid_from),
  constraint manager_team_reference_positive_evidence
    check (evidence_rows > 0),
  constraint manager_team_reference_natural_key
    unique (manager_key, team_key, valid_from)
);

comment on table public.manager_team_reference is
  'Date-aware manager-to-team interpretation derived from the management spreadsheet; never an official sales fact source.';

create index manager_team_reference_lookup_idx
  on public.manager_team_reference (manager_key, valid_from desc, valid_to);

create index manager_team_reference_source_coverage_idx
  on public.manager_team_reference (source_updated_through desc);

alter table public.manager_team_reference enable row level security;

revoke all on table public.manager_team_reference from anon, authenticated;
grant select on table public.manager_team_reference to authenticated;

create policy manager_team_reference_select_authorized
on public.manager_team_reference
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    join public.user_roles as user_role
      on user_role.user_id = profile.id
    where profile.id = (select auth.uid())
      and profile.status = 'active'
      and user_role.role::text in ('super_admin', 'viewer')
  )
);

-- Collapse the spreadsheet's sale-level rows into a small, date-effective
-- management dimension. A same-day tie is excluded instead of guessed.
with observations as (
  select
    row.sale_date,
    btrim(row.row_data ->> 'Gerente') as manager_name,
    btrim(row.row_data ->> 'Equipe') as team_name,
    row.source_file_name,
    row.source_sheet_name,
    row.source_updated_through
  from public.internal_sales_spreadsheet_rows as row
  where row.sale_date is not null
    and nullif(btrim(row.row_data ->> 'Gerente'), '') is not null
    and nullif(btrim(row.row_data ->> 'Equipe'), '') is not null
),
normalized as (
  select
    sale_date,
    lower(regexp_replace(translate(
      manager_name,
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
      'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc'
    ), '\s+', ' ', 'g'))
      as manager_key,
    manager_name,
    lower(regexp_replace(translate(
      team_name,
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüç',
      'AAAAAEEEEIIIIOOOOOUUUUCaaaaaeeeeiiiiooooouuuuc'
    ), '\s+', ' ', 'g'))
      as team_key,
    team_name,
    source_file_name,
    source_sheet_name,
    source_updated_through
  from observations
),
daily_counts as (
  select
    manager_key,
    sale_date,
    team_key,
    (array_agg(manager_name order by manager_name))[1] as manager_name,
    (array_agg(team_name order by team_name))[1] as team_name,
    max(source_file_name) as source_file_name,
    max(source_sheet_name) as source_sheet_name,
    max(source_updated_through) as source_updated_through,
    count(*)::integer as evidence_rows
  from normalized
  group by manager_key, sale_date, team_key
),
daily_ranked as (
  select
    daily_counts.*,
    row_number() over (
      partition by manager_key, sale_date
      order by evidence_rows desc, team_key
    ) as position,
    lead(evidence_rows) over (
      partition by manager_key, sale_date
      order by evidence_rows desc, team_key
    ) as runner_up_rows
  from daily_counts
),
daily_choice as (
  select *
  from daily_ranked
  where position = 1
    and (runner_up_rows is null or evidence_rows > runner_up_rows)
),
marked as (
  select
    daily_choice.*,
    case
      when lag(team_key) over (
        partition by manager_key order by sale_date
      ) is distinct from team_key then 1
      else 0
    end as starts_new_segment
  from daily_choice
),
grouped as (
  select
    marked.*,
    sum(starts_new_segment) over (
      partition by manager_key order by sale_date
    ) as segment_number
  from marked
),
segments as (
  select
    manager_key,
    team_key,
    segment_number,
    (array_agg(manager_name order by sale_date desc))[1] as manager_name,
    (array_agg(team_name order by sale_date desc))[1] as team_name,
    min(sale_date) as valid_from,
    max(source_file_name) as source_file_name,
    max(source_sheet_name) as source_sheet_name,
    max(source_updated_through) as source_updated_through,
    sum(evidence_rows)::integer as evidence_rows
  from grouped
  group by manager_key, team_key, segment_number
),
manager_stats as (
  select
    manager_key,
    count(distinct team_key) > 1 as review_required
  from segments
  group by manager_key
),
dated_segments as (
  select
    segments.*,
    lead(valid_from) over (
      partition by manager_key order by valid_from, segment_number
    ) as next_valid_from,
    manager_stats.review_required
  from segments
  join manager_stats using (manager_key)
)
insert into public.manager_team_reference (
  manager_key,
  manager_name,
  team_key,
  team_name,
  valid_from,
  valid_to,
  source_file_name,
  source_sheet_name,
  source_updated_through,
  evidence_rows,
  review_required
)
select
  manager_key,
  manager_name,
  team_key,
  team_name,
  valid_from,
  next_valid_from - 1,
  source_file_name,
  source_sheet_name,
  source_updated_through,
  evidence_rows,
  review_required
from dated_segments;
-- END COMPONENT: supabase/migrations/20260830162242_add_manager_team_reference.sql

-- BEGIN COMPONENT: supabase/migrations/20260831003640_add_integration_failure_diagnostics.sql
-- Sanitized operational diagnostics for authenticated internal integrations.
-- This table never stores tokens, request/response bodies, customer data or
-- commercial facts. It exists only to identify the failing integration layer.

create table public.integration_failure_diagnostics (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  occurred_at timestamptz not null default now(),
  function_slug text not null,
  function_version text not null,
  operation text not null,
  period_start date,
  period_end date,
  http_status smallint not null,
  error_code text not null,
  constraint integration_failure_diagnostics_status_range
    check (http_status between 0 and 599),
  constraint integration_failure_diagnostics_function_slug_not_blank
    check (btrim(function_slug) <> ''),
  constraint integration_failure_diagnostics_function_version_not_blank
    check (btrim(function_version) <> ''),
  constraint integration_failure_diagnostics_operation_not_blank
    check (btrim(operation) <> ''),
  constraint integration_failure_diagnostics_error_code_format
    check (error_code ~ '^[a-z0-9][a-z0-9_:-]{0,79}$'),
  constraint integration_failure_diagnostics_period_order
    check (period_start is null or period_end is null or period_end >= period_start)
);

comment on table public.integration_failure_diagnostics is
  'Sanitized internal integration failures; excludes tokens, payloads, customer data and commercial facts.';

create index integration_failure_diagnostics_recent_idx
  on public.integration_failure_diagnostics (occurred_at desc);

alter table public.integration_failure_diagnostics enable row level security;

revoke all on table public.integration_failure_diagnostics from anon, authenticated;
grant insert on table public.integration_failure_diagnostics to authenticated;

create policy integration_failure_diagnostics_insert_authorized
on public.integration_failure_diagnostics
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.profiles as profile
    join public.user_roles as user_role
      on user_role.user_id = profile.id
    where profile.id = (select auth.uid())
      and profile.status = 'active'
      and user_role.role::text in ('super_admin', 'viewer')
  )
);
-- END COMPONENT: supabase/migrations/20260831003640_add_integration_failure_diagnostics.sql

-- BEGIN COMPONENT: supabase/migrations/20260831013118_allow_authorized_diagnostic_reads.sql
-- Allow active internal roles to read sanitized integration health signals.
-- Rows contain only operational metadata and never tokens, payloads, customer
-- data or commercial facts.

create index if not exists integration_failure_diagnostics_operation_recent_idx
  on public.integration_failure_diagnostics (operation, occurred_at desc);

grant select on table public.integration_failure_diagnostics to authenticated;

create policy integration_failure_diagnostics_select_authorized
on public.integration_failure_diagnostics
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    join public.user_roles as user_role
      on user_role.user_id = profile.id
    where profile.id = (select auth.uid())
      and profile.status = 'active'
      and user_role.role::text in ('super_admin', 'viewer')
  )
);
-- END COMPONENT: supabase/migrations/20260831013118_allow_authorized_diagnostic_reads.sql

-- BEGIN COMPONENT: supabase/migrations/20260901150000_add_portal_conversations_and_rbac.sql
-- Gralha Indicadores: persistent conversations and role/team access model.
-- Business facts remain in the live Pipeimob and Vista integrations.

create schema if not exists private;

alter table public.profiles
  add column if not exists display_name text,
  add column if not exists access_role text,
  add column if not exists updated_at timestamptz not null default now();

update public.profiles as profile
set access_role = case
  when exists (
    select 1
    from public.user_roles as user_role
    where user_role.user_id = profile.id
      and user_role.role::text = 'super_admin'
  ) then 'cmo'
  else 'team_manager'
end
where access_role is null;

alter table public.profiles
  alter column access_role set default 'team_manager',
  alter column access_role set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_access_role_valid'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_access_role_valid
      check (access_role in (
        'ceo',
        'cso',
        'cmo',
        'store_director',
        'team_manager'
      ));
  end if;
end
$$;

create table if not exists public.teams (
  team_key text primary key,
  team_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teams_key_not_blank check (btrim(team_key) <> ''),
  constraint teams_name_not_blank check (btrim(team_name) <> '')
);

insert into public.teams (team_key, team_name)
select distinct on (source.team_key)
  source.team_key,
  source.team_name
from (
  select team_key, team_name, source_updated_through
  from public.sales_team_reference
  union all
  select team_key, team_name, source_updated_through
  from public.manager_team_reference
) as source
where nullif(btrim(source.team_key), '') is not null
  and nullif(btrim(source.team_name), '') is not null
order by source.team_key, source.source_updated_through desc nulls last
on conflict (team_key) do update
set team_name = excluded.team_name,
    updated_at = now();

create table if not exists public.user_team_access (
  user_id uuid not null references public.profiles(id) on delete cascade,
  team_key text not null references public.teams(team_key) on update cascade,
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  primary key (user_id, team_key)
);

create index if not exists user_team_access_team_key_idx
  on public.user_team_access (team_key, user_id);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_title_not_blank check (btrim(title) <> ''),
  constraint conversations_title_length check (char_length(title) <= 160)
);

create index if not exists conversations_user_updated_idx
  on public.conversations (user_id, updated_at desc, id);

create table if not exists public.conversation_messages (
  id bigint generated always as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null,
  content text not null,
  visualization jsonb,
  created_at timestamptz not null default now(),
  constraint conversation_messages_role_valid
    check (role in ('user', 'assistant')),
  constraint conversation_messages_content_not_blank
    check (btrim(content) <> ''),
  constraint conversation_messages_content_length
    check (char_length(content) <= 12000),
  constraint conversation_messages_visualization_object
    check (visualization is null or jsonb_typeof(visualization) = 'object')
);

create index if not exists conversation_messages_conversation_cursor_idx
  on public.conversation_messages (conversation_id, id);

create index if not exists conversation_messages_user_id_idx
  on public.conversation_messages (user_id);

create table if not exists public.user_management_audit (
  id bigint generated always as identity primary key,
  actor_user_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint user_management_audit_action_not_blank
    check (btrim(action) <> ''),
  constraint user_management_audit_details_object
    check (jsonb_typeof(details) = 'object')
);

create index if not exists user_management_audit_created_idx
  on public.user_management_audit (created_at desc, id);

create index if not exists user_management_audit_target_idx
  on public.user_management_audit (target_user_id, created_at desc);

create or replace function private.current_user_is_executive()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.status::text = 'active'
      and profile.access_role in ('ceo', 'cso', 'cmo')
  )
$$;

revoke all on function private.current_user_is_executive()
  from public, anon, authenticated, service_role;

-- The helper is referenced by RLS policies. The private schema is not exposed
-- by the Data API, so this grant permits policy evaluation without publishing
-- a callable RPC endpoint.
grant usage on schema private to authenticated;
grant execute on function private.current_user_is_executive() to authenticated;

alter table public.teams enable row level security;
alter table public.user_team_access enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_messages enable row level security;
alter table public.user_management_audit enable row level security;

revoke all on table public.teams from anon, authenticated;
revoke all on table public.user_team_access from anon, authenticated;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.conversation_messages from anon, authenticated;
revoke all on table public.user_management_audit from anon, authenticated;

grant select on table public.teams to authenticated;
grant select on table public.user_team_access to authenticated;
grant select, insert, update, delete on table public.conversations to authenticated;
grant select, insert, delete on table public.conversation_messages to authenticated;
grant usage, select on sequence public.conversation_messages_id_seq to authenticated;

grant all on table public.teams to service_role;
grant all on table public.user_team_access to service_role;
grant all on table public.conversations to service_role;
grant all on table public.conversation_messages to service_role;
grant all on table public.user_management_audit to service_role;
grant usage, select on sequence public.conversation_messages_id_seq to service_role;
grant usage, select on sequence public.user_management_audit_id_seq to service_role;

drop policy if exists teams_select_authorized on public.teams;
create policy teams_select_authorized
on public.teams
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.status::text = 'active'
      and (
        profile.access_role in ('ceo', 'cso', 'cmo')
        or exists (
          select 1
          from public.user_team_access as access
          where access.user_id = profile.id
            and access.team_key = teams.team_key
        )
      )
  )
);

drop policy if exists user_team_access_select_scope on public.user_team_access;
create policy user_team_access_select_scope
on public.user_team_access
for select
to authenticated
using (
  user_id = (select auth.uid())
  or (select private.current_user_is_executive())
);

drop policy if exists conversations_select_own on public.conversations;
create policy conversations_select_own
on public.conversations
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists conversations_insert_own on public.conversations;
create policy conversations_insert_own
on public.conversations
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists conversations_update_own on public.conversations;
create policy conversations_update_own
on public.conversations
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists conversations_delete_own on public.conversations;
create policy conversations_delete_own
on public.conversations
for delete
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists conversation_messages_select_own on public.conversation_messages;
create policy conversation_messages_select_own
on public.conversation_messages
for select
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.conversations as conversation
    where conversation.id = conversation_messages.conversation_id
      and conversation.user_id = (select auth.uid())
  )
);

drop policy if exists conversation_messages_insert_own on public.conversation_messages;
create policy conversation_messages_insert_own
on public.conversation_messages
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.conversations as conversation
    where conversation.id = conversation_messages.conversation_id
      and conversation.user_id = (select auth.uid())
  )
);

drop policy if exists conversation_messages_delete_own on public.conversation_messages;
create policy conversation_messages_delete_own
on public.conversation_messages
for delete
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.conversations as conversation
    where conversation.id = conversation_messages.conversation_id
      and conversation.user_id = (select auth.uid())
  )
);

drop policy if exists profiles_select_self_or_executive on public.profiles;
create policy profiles_select_self_or_executive
on public.profiles
for select
to authenticated
using (
  id = (select auth.uid())
  or (select private.current_user_is_executive())
);

drop policy if exists user_management_audit_select_executive
  on public.user_management_audit;
create policy user_management_audit_select_executive
on public.user_management_audit
for select
to authenticated
using ((select private.current_user_is_executive()));

comment on table public.conversations is
  'Private per-user Gralha Indicadores conversation history.';
comment on table public.conversation_messages is
  'Visible chat messages only; never stores access tokens or raw integration payloads.';
comment on table public.user_team_access is
  'Date-independent portal authorization scope. Commercial attribution remains separate.';
-- END COMPONENT: supabase/migrations/20260901150000_add_portal_conversations_and_rbac.sql

-- BEGIN COMPONENT: supabase/migrations/20260901182000_add_conversation_message_idempotency.sql
alter table public.conversation_messages
  add column if not exists request_id uuid;

create unique index if not exists conversation_messages_request_role_uidx
  on public.conversation_messages (conversation_id, role, request_id)
  where request_id is not null;

comment on column public.conversation_messages.request_id is
  'Client-generated idempotency key used to prevent duplicate messages after safe retries.';
-- END COMPONENT: supabase/migrations/20260901182000_add_conversation_message_idempotency.sql

-- BEGIN COMPONENT: supabase/migrations/20260901191000_tune_portal_policies_and_indexes.sql
drop policy if exists "Users and superadmins can view profiles" on public.profiles;

create index if not exists user_management_audit_actor_idx
  on public.user_management_audit (actor_user_id, created_at desc);

create index if not exists user_team_access_created_by_idx
  on public.user_team_access (created_by)
  where created_by is not null;
-- END COMPONENT: supabase/migrations/20260901191000_tune_portal_policies_and_indexes.sql

-- BEGIN COMPONENT: tests/fixtures/baseline_least_privilege_candidate.sql
-- TEST CANDIDATE ONLY. Final grants for the disposable full-baseline replay.
do $$ begin
  if current_database() <> 'gralha_baseline_ci' then
    raise exception 'Only disposable gralha_baseline_ci is allowed';
  end if;
end $$;

revoke all on all tables in schema public from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;

grant select on table public.profiles to authenticated;
grant select on table public.user_roles to authenticated;
grant select on table public.internal_sales_spreadsheet_rows to authenticated;
grant select on table public.sales_team_reference to authenticated;
grant select on table public.manager_team_reference to authenticated;
grant select, insert on table public.integration_failure_diagnostics to authenticated;
grant select on table public.teams to authenticated;
grant select on table public.user_team_access to authenticated;
grant select, insert, update, delete on table public.conversations to authenticated;
grant select, insert, delete on table public.conversation_messages to authenticated;
grant usage, select on sequence public.conversation_messages_id_seq to authenticated;

grant all on all tables in schema public to service_role;
grant usage, select, update on all sequences in schema public to service_role;

revoke all on schema validation from public, anon, authenticated, service_role;
revoke all on all tables in schema validation
  from public, anon, authenticated, service_role;
revoke all on all sequences in schema validation
  from public, anon, authenticated, service_role;

revoke all on function public.sync_validation_user_access()
  from public, anon, authenticated, service_role;
revoke all on function public.get_validation_sales_reconciliation(date, date)
  from public, anon, authenticated, service_role;
grant execute on function public.get_validation_sales_reconciliation(date, date)
  to service_role;
-- END COMPONENT: tests/fixtures/baseline_least_privilege_candidate.sql
