import assert from 'node:assert/strict';
import {
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const cliFilename =
  '20260904150012_establish_sanitized_schema_baseline.sql';
const destination = resolve(
  root,
  'docs/migrations/baseline-candidate',
  cliFilename,
);
const components = [
  'tests/fixtures/identity_baseline_candidate.sql',
  'tests/fixtures/commercial_baseline_candidate.sql',
  'docs/migrations/history-review/20260821133318_add_consolidated_sales_fiscal_broker_index.sql.txt',
  'docs/migrations/history-review/20260821133813_create_validation_sales_reconciliation_rpc.sql.txt',
  'supabase/migrations/20260830162242_add_manager_team_reference.sql',
  'supabase/migrations/20260831003640_add_integration_failure_diagnostics.sql',
  'supabase/migrations/20260831013118_allow_authorized_diagnostic_reads.sql',
  'supabase/migrations/20260901150000_add_portal_conversations_and_rbac.sql',
  'supabase/migrations/20260901182000_add_conversation_message_idempotency.sql',
  'supabase/migrations/20260901191000_tune_portal_policies_and_indexes.sql',
  'tests/fixtures/baseline_least_privilege_candidate.sql',
];

const sections = components.map((path) => {
  const content = readFileSync(resolve(root, path), 'utf8').trimEnd();
  assert.ok(content, `Empty baseline component: ${path}`);
  return `-- BEGIN COMPONENT: ${path}\n${content}\n-- END COMPONENT: ${path}`;
});
const header = `-- REVIEW CANDIDATE ONLY. Not an active Supabase migration.
-- Filename generated by Supabase CLI 2.20.3 in GitHub Actions run 33886952900.
-- This combined baseline is intentionally stored outside supabase/migrations.
-- It is executable only in the disposable database gralha_baseline_ci.
-- No user, conversation, sale, broker/team seed, secret, or credential is included.
-- Production rollout still requires separate history reconciliation and approval.`;
const output = `${header}\n\n${sections.join('\n\n')}\n`;

assert.doesNotMatch(
  output,
  /[a-z0-9._%+-]+@(?!example\.test)[a-z0-9.-]+\.[a-z]{2,}/i,
);
assert.doesNotMatch(output, /eyJ[A-Za-z0-9_-]{20,}|sb_secret_|sbp_[A-Za-z0-9]{20,}/);
assert.match(output, /current_database\(\) <> 'gralha_baseline_ci'/);
assert.doesNotMatch(output, /INICIAR-VALIDACAO-EQUIPES-GRALHA/);

mkdirSync(dirname(destination), { recursive: true });
writeFileSync(destination, output, { encoding: 'utf8', mode: 0o644 });
console.log(destination.slice(root.length + 1));
