-- TEST CANDIDATE ONLY. Structural DDL recovered from catalog metadata.
-- No business rows, broker/team seeds, credentials, or production authorization.
do $$ begin
  if current_database() <> 'gralha_baseline_ci' then
    raise exception 'Only disposable gralha_baseline_ci is allowed';
  end if;
end $$;

create schema if not exists validation;

create table "public"."internal_sales_spreadsheet_rows" (
  "id" bigint generated by default as identity not null,
  "source_file_name" text not null,
  "source_sheet_name" text default 'VENDAS'::text not null,
  "source_row_number" integer not null,
  "sale_year" integer,
  "sale_date" date,
  "property_code" text,
  "broker_name" text,
  "broker_key" text,
  "team_name" text,
  "team_key" text,
  "neighborhood" text,
  "vgv" numeric,
  "row_data" jsonb not null,
  "row_formulas" jsonb default '{}'::jsonb not null,
  "source_updated_through" date not null,
  "imported_at" timestamp with time zone default now() not null
);

create table "public"."sales_team_reference" (
  "id" bigint generated by default as identity not null,
  "source_file_name" text not null,
  "source_row_number" integer not null,
  "sale_date" date not null,
  "property_code" text not null,
  "broker_key" text not null,
  "broker_name" text not null,
  "team_key" text not null,
  "team_name" text not null,
  "source_updated_through" date not null,
  "created_at" timestamp with time zone default now() not null
);

create table "validation"."broker_system_identifiers" (
  "id" bigint generated always as identity not null,
  "broker_id" bigint not null,
  "source_system" text not null,
  "external_id" text not null,
  "valid_from" date,
  "valid_to" date,
  "created_at" timestamp with time zone default now() not null
);

create table "validation"."broker_team_history" (
  "id" bigint generated always as identity not null,
  "broker_id" bigint not null,
  "team_id" bigint not null,
  "valid_from" date not null,
  "valid_to" date,
  "change_source" text not null,
  "recorded_at" timestamp with time zone default now() not null,
  "recorded_by" text not null
);

create table "validation"."brokers" (
  "id" bigint generated always as identity not null,
  "display_name" text not null,
  "normalized_name" text not null,
  "active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "validation"."consolidated_sales" (
  "id" bigint generated always as identity not null,
  "pipeimob_transaction_id" text,
  "vista_deal_id" text,
  "property_code" text,
  "official_sale_date" date,
  "vista_gain_date" date,
  "delay_hours" numeric(12,2),
  "official_value" numeric(16,2),
  "vista_value" numeric(16,2),
  "value_difference" numeric(16,2) generated always as (CASE
    WHEN official_value IS NOT NULL AND vista_value IS NOT NULL THEN vista_value - official_value
    ELSE NULL::numeric
END) stored,
  "commercial_broker_id" bigint,
  "commercial_broker_name_snapshot" text,
  "fiscal_broker_id" bigint,
  "fiscal_broker_name_snapshot" text,
  "team_at_sale_id" bigint,
  "team_name_snapshot" text,
  "reconciliation_status" text not null,
  "issues" text[] default '{}'::text[] not null,
  "match_method" text default 'unmatched'::text not null,
  "match_confidence" numeric(5,4),
  "reconciled_at" timestamp with time zone default now() not null,
  "source_version" text default 'validation-v1'::text not null
);

create table "validation"."pipeimob_sales" (
  "transaction_id" text not null,
  "contract_code" text,
  "property_code" text not null,
  "signature_date" date not null,
  "contract_value" numeric(16,2) not null,
  "fiscal_broker_id" bigint,
  "fiscal_broker_name_snapshot" text,
  "sale_status" text default 'active'::text not null,
  "source_run_id" bigint not null,
  "source_record_hash" text not null,
  "ingested_at" timestamp with time zone default now() not null
);

create table "validation"."reconciliation_events" (
  "id" bigint generated always as identity not null,
  "consolidated_sale_id" bigint not null,
  "event_type" text not null,
  "previous_status" text,
  "new_status" text not null,
  "reason" text,
  "changed_at" timestamp with time zone default now() not null,
  "changed_by" text not null,
  "details" jsonb default '{}'::jsonb not null
);

create table "validation"."source_ingestion_runs" (
  "id" bigint generated always as identity not null,
  "source_system" text not null,
  "source_filename" text,
  "source_sha256" text not null,
  "period_start" date,
  "period_end" date,
  "row_count" integer not null,
  "import_status" text default 'completed'::text not null,
  "imported_at" timestamp with time zone default now() not null,
  "imported_by" text not null,
  "metadata" jsonb default '{}'::jsonb not null
);

create table "validation"."teams" (
  "id" bigint generated always as identity not null,
  "stable_code" text not null,
  "display_name" text not null,
  "active" boolean default true not null,
  "valid_from" date,
  "valid_to" date,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table "validation"."vista_gains" (
  "deal_id" text not null,
  "property_code" text,
  "gain_date" date,
  "deal_value" numeric(16,2),
  "commercial_broker_id" bigint,
  "commercial_broker_external_id" text,
  "commercial_broker_name_snapshot" text,
  "stage_name" text,
  "crm_status" text default 'GANHO'::text not null,
  "last_update_at" timestamp with time zone,
  "source_run_id" bigint not null,
  "source_record_hash" text not null,
  "ingested_at" timestamp with time zone default now() not null
);

alter table "public"."internal_sales_spreadsheet_rows" add constraint "internal_sales_spreadsheet_rows_pkey" PRIMARY KEY (id);
alter table "public"."sales_team_reference" add constraint "sales_team_reference_pkey" PRIMARY KEY (id);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_pkey" PRIMARY KEY (id);
alter table "validation"."broker_team_history" add constraint "broker_team_history_pkey" PRIMARY KEY (id);
alter table "validation"."brokers" add constraint "brokers_pkey" PRIMARY KEY (id);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pkey" PRIMARY KEY (id);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_pkey" PRIMARY KEY (transaction_id);
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_pkey" PRIMARY KEY (id);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_pkey" PRIMARY KEY (id);
alter table "validation"."teams" add constraint "teams_pkey" PRIMARY KEY (id);
alter table "validation"."vista_gains" add constraint "vista_gains_pkey" PRIMARY KEY (deal_id);
alter table "public"."internal_sales_spreadsheet_rows" add constraint "internal_sales_spreadsheet_rows_source_key" UNIQUE (source_file_name, source_sheet_name, source_row_number);
alter table "public"."sales_team_reference" add constraint "sales_team_reference_source_key" UNIQUE (source_file_name, source_row_number);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_source_system_external_id_key" UNIQUE (source_system, external_id);
alter table "validation"."broker_team_history" add constraint "broker_team_history_broker_id_team_id_valid_from_key" UNIQUE (broker_id, team_id, valid_from);
alter table "validation"."brokers" add constraint "brokers_normalized_name_key" UNIQUE (normalized_name);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pipeimob_transaction_id_key" UNIQUE (pipeimob_transaction_id);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_deal_id_key" UNIQUE (vista_deal_id);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_source_system_source_sha256_key" UNIQUE (source_system, source_sha256);
alter table "validation"."teams" add constraint "teams_stable_code_key" UNIQUE (stable_code);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_check" CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_external_id_check" CHECK (length(btrim(external_id)) > 0);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_source_system_check" CHECK (source_system = ANY (ARRAY['pipeimob'::text, 'vista'::text, 'internal'::text]));
alter table "validation"."broker_team_history" add constraint "broker_team_history_change_source_check" CHECK (change_source = ANY (ARRAY['vista'::text, 'pipeimob'::text, 'administration'::text, 'import'::text]));
alter table "validation"."broker_team_history" add constraint "broker_team_history_check" CHECK (valid_to IS NULL OR valid_to >= valid_from);
alter table "validation"."brokers" add constraint "brokers_display_name_check" CHECK (length(btrim(display_name)) > 0);
alter table "validation"."brokers" add constraint "brokers_normalized_name_check" CHECK (length(btrim(normalized_name)) > 0);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_match_confidence_check" CHECK (match_confidence IS NULL OR match_confidence >= 0::numeric AND match_confidence <= 1::numeric);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_match_method_check" CHECK (match_method = ANY (ARRAY['vista_deal_id'::text, 'client_property'::text, 'property_value_date'::text, 'property_client_assisted'::text, 'manual'::text, 'unmatched'::text]));
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_official_value_check" CHECK (official_value IS NULL OR official_value >= 0::numeric);
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_reconciliation_status_check" CHECK (reconciliation_status = ANY (ARRAY['CONCILIADO'::text, 'PIPEIMOB_SEM_GANHO_VISTA'::text, 'VISTA_SEM_CONTRATO_PIPEIMOB'::text, 'DIVERGENCIA_VALOR'::text, 'DIVERGENCIA_DATA'::text, 'DIVERGENCIA_CORRETOR'::text, 'SEM_VINCULO_AUTOMATICO'::text, 'CANCELADO_OU_REVERTIDO'::text, 'DADO_FONTE_INCOMPLETO'::text]));
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_value_check" CHECK (vista_value IS NULL OR vista_value >= 0::numeric);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_contract_value_check" CHECK (contract_value >= 0::numeric);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_property_code_check" CHECK (length(btrim(property_code)) > 0);
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_sale_status_check" CHECK (sale_status = ANY (ARRAY['active'::text, 'cancelled'::text, 'reversed'::text]));
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_transaction_id_check" CHECK (length(btrim(transaction_id)) > 0);
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_event_type_check" CHECK (event_type = ANY (ARRAY['created'::text, 'reconciled'::text, 'status_changed'::text, 'manually_reviewed'::text, 'cancelled'::text, 'reversed'::text]));
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_import_status_check" CHECK (import_status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text, 'rolled_back'::text]));
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_row_count_check" CHECK (row_count >= 0);
alter table "validation"."source_ingestion_runs" add constraint "source_ingestion_runs_source_system_check" CHECK (source_system = ANY (ARRAY['pipeimob'::text, 'vista'::text, 'manual'::text]));
alter table "validation"."teams" add constraint "teams_check" CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from);
alter table "validation"."teams" add constraint "teams_display_name_check" CHECK (length(btrim(display_name)) > 0);
alter table "validation"."teams" add constraint "teams_stable_code_check" CHECK (length(btrim(stable_code)) > 0);
alter table "validation"."vista_gains" add constraint "vista_gains_crm_status_check" CHECK (crm_status = 'GANHO'::text);
alter table "validation"."vista_gains" add constraint "vista_gains_deal_id_check" CHECK (length(btrim(deal_id)) > 0);
alter table "validation"."vista_gains" add constraint "vista_gains_deal_value_check" CHECK (deal_value IS NULL OR deal_value >= 0::numeric);
alter table "validation"."broker_system_identifiers" add constraint "broker_system_identifiers_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."broker_team_history" add constraint "broker_team_history_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."broker_team_history" add constraint "broker_team_history_team_id_fkey" FOREIGN KEY (team_id) REFERENCES validation.teams(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_commercial_broker_id_fkey" FOREIGN KEY (commercial_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_fiscal_broker_id_fkey" FOREIGN KEY (fiscal_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_pipeimob_transaction_id_fkey" FOREIGN KEY (pipeimob_transaction_id) REFERENCES validation.pipeimob_sales(transaction_id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_team_at_sale_id_fkey" FOREIGN KEY (team_at_sale_id) REFERENCES validation.teams(id) ON DELETE RESTRICT;
alter table "validation"."consolidated_sales" add constraint "consolidated_sales_vista_deal_id_fkey" FOREIGN KEY (vista_deal_id) REFERENCES validation.vista_gains(deal_id) ON DELETE RESTRICT;
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_fiscal_broker_id_fkey" FOREIGN KEY (fiscal_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."pipeimob_sales" add constraint "pipeimob_sales_source_run_id_fkey" FOREIGN KEY (source_run_id) REFERENCES validation.source_ingestion_runs(id) ON DELETE RESTRICT;
alter table "validation"."reconciliation_events" add constraint "reconciliation_events_consolidated_sale_id_fkey" FOREIGN KEY (consolidated_sale_id) REFERENCES validation.consolidated_sales(id) ON DELETE RESTRICT;
alter table "validation"."vista_gains" add constraint "vista_gains_commercial_broker_id_fkey" FOREIGN KEY (commercial_broker_id) REFERENCES validation.brokers(id) ON DELETE RESTRICT;
alter table "validation"."vista_gains" add constraint "vista_gains_source_run_id_fkey" FOREIGN KEY (source_run_id) REFERENCES validation.source_ingestion_runs(id) ON DELETE RESTRICT;

CREATE INDEX internal_sales_spreadsheet_rows_broker_date_idx ON public.internal_sales_spreadsheet_rows USING btree (broker_key, sale_date);
CREATE INDEX internal_sales_spreadsheet_rows_property_date_idx ON public.internal_sales_spreadsheet_rows USING btree (property_code, sale_date);
CREATE INDEX internal_sales_spreadsheet_rows_team_date_idx ON public.internal_sales_spreadsheet_rows USING btree (team_key, sale_date);
CREATE INDEX sales_team_reference_lookup_idx ON public.sales_team_reference USING btree (broker_key, sale_date, property_code);
CREATE INDEX broker_system_identifiers_broker_idx ON validation.broker_system_identifiers USING btree (broker_id);
CREATE INDEX broker_team_history_broker_period_idx ON validation.broker_team_history USING btree (broker_id, valid_from, valid_to);
CREATE INDEX broker_team_history_team_idx ON validation.broker_team_history USING btree (team_id);
CREATE INDEX consolidated_sales_commercial_broker_period_idx ON validation.consolidated_sales USING btree (commercial_broker_id, official_sale_date);
CREATE INDEX consolidated_sales_fiscal_broker_period_idx ON validation.consolidated_sales USING btree (fiscal_broker_id, official_sale_date DESC);
CREATE INDEX consolidated_sales_pending_idx ON validation.consolidated_sales USING btree (reconciliation_status, official_sale_date) WHERE (reconciliation_status <> 'CONCILIADO'::text);
CREATE INDEX consolidated_sales_period_status_idx ON validation.consolidated_sales USING btree (official_sale_date, reconciliation_status);
CREATE INDEX consolidated_sales_team_period_idx ON validation.consolidated_sales USING btree (team_at_sale_id, official_sale_date);
CREATE INDEX pipeimob_sales_fiscal_broker_idx ON validation.pipeimob_sales USING btree (fiscal_broker_id);
CREATE INDEX pipeimob_sales_match_idx ON validation.pipeimob_sales USING btree (property_code, contract_value, signature_date);
CREATE INDEX pipeimob_sales_period_idx ON validation.pipeimob_sales USING btree (signature_date, transaction_id);
CREATE INDEX pipeimob_sales_source_run_idx ON validation.pipeimob_sales USING btree (source_run_id);
CREATE INDEX reconciliation_events_sale_idx ON validation.reconciliation_events USING btree (consolidated_sale_id, changed_at);
CREATE INDEX source_runs_period_idx ON validation.source_ingestion_runs USING btree (source_system, period_start, period_end);
CREATE INDEX vista_gains_commercial_broker_idx ON validation.vista_gains USING btree (commercial_broker_id);
CREATE INDEX vista_gains_match_idx ON validation.vista_gains USING btree (property_code, deal_value, gain_date);
CREATE INDEX vista_gains_period_idx ON validation.vista_gains USING btree (gain_date, deal_id);
CREATE INDEX vista_gains_source_run_idx ON validation.vista_gains USING btree (source_run_id);

-- Defense in depth. The validation schema remains outside the Data API.
alter table "public"."internal_sales_spreadsheet_rows" enable row level security;
alter table "public"."sales_team_reference" enable row level security;
alter table "validation"."broker_system_identifiers" enable row level security;
alter table "validation"."broker_team_history" enable row level security;
alter table "validation"."brokers" enable row level security;
alter table "validation"."consolidated_sales" enable row level security;
alter table "validation"."pipeimob_sales" enable row level security;
alter table "validation"."reconciliation_events" enable row level security;
alter table "validation"."source_ingestion_runs" enable row level security;
alter table "validation"."teams" enable row level security;
alter table "validation"."vista_gains" enable row level security;

revoke all on schema validation from public, anon, authenticated, service_role;
revoke all on all tables in schema validation from public, anon, authenticated, service_role;
revoke all on all sequences in schema validation from public, anon, authenticated, service_role;

revoke all on table public.internal_sales_spreadsheet_rows from public, anon, authenticated;
revoke all on table public.sales_team_reference from public, anon, authenticated;
grant select on table public.internal_sales_spreadsheet_rows to authenticated;
grant select on table public.sales_team_reference to authenticated;
grant all on table public.internal_sales_spreadsheet_rows to service_role;
grant all on table public.sales_team_reference to service_role;
grant usage, select, update on sequence public.internal_sales_spreadsheet_rows_id_seq to service_role;
grant usage, select, update on sequence public.sales_team_reference_id_seq to service_role;

create policy "super admins can read full sales spreadsheet"
on public.internal_sales_spreadsheet_rows for select to authenticated
using (public.is_active_super_admin((select auth.uid())));

create policy "active indicator users can read team reference"
on public.sales_team_reference for select to authenticated
using (public.is_active_user((select auth.uid())));

